[project]
name = "protonn"
dynamic = ["dependencies", "version"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {attr = "protonn._version.VERSION"}

[tool.setuptools.packages.find]
where = ["."]
include = ["protonn*"]

[tool.black]
line-length = 100
